
// This file was autogenerated by PeakRDL-uvm
package awr2243_control_csr_ral_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - awr2243_control_csr::VERSION
    class awr2243_control_csr__VERSION extends uvm_reg;
        rand uvm_reg_field version;

        function new(string name = "awr2243_control_csr__VERSION");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.version = new("version");
            this.version.configure(this, 32, 0, "RO", 0, 'h43530100, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__VERSION

    // reg - awr2243_control_csr::CONTROL
    class awr2243_control_csr__CONTROL extends uvm_reg;
        rand uvm_reg_field start_init;
        rand uvm_reg_field start_sensor;
        rand uvm_reg_field stop_sensor;
        rand uvm_reg_field hard_reset;
        rand uvm_reg_field clear_error;

        function new(string name = "awr2243_control_csr__CONTROL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.start_init = new("start_init");
            this.start_init.configure(this, 1, 0, "WO", 1, 'h0, 1, 1, 0);
            this.start_sensor = new("start_sensor");
            this.start_sensor.configure(this, 1, 1, "WO", 1, 'h0, 1, 1, 0);
            this.stop_sensor = new("stop_sensor");
            this.stop_sensor.configure(this, 1, 2, "WO", 1, 'h0, 1, 1, 0);
            this.hard_reset = new("hard_reset");
            this.hard_reset.configure(this, 1, 3, "WO", 1, 'h0, 1, 1, 0);
            this.clear_error = new("clear_error");
            this.clear_error.configure(this, 1, 4, "WO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__CONTROL

    // reg - awr2243_control_csr::STATUS
    class awr2243_control_csr__STATUS extends uvm_reg;
        rand uvm_reg_field busy;
        rand uvm_reg_field done;
        rand uvm_reg_field done_sticky;
        rand uvm_reg_field err_sticky;
        rand uvm_reg_field irq_seen_sticky;
        rand uvm_reg_field fault_seen_sticky;

        function new(string name = "awr2243_control_csr__STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.busy = new("busy");
            this.busy.configure(this, 1, 0, "RO", 1, 'h0, 0, 1, 0);
            this.done = new("done");
            this.done.configure(this, 1, 1, "RO", 1, 'h0, 0, 1, 0);
            this.done_sticky = new("done_sticky");
            this.done_sticky.configure(this, 1, 8, "RO", 1, 'h0, 0, 1, 0);
            this.err_sticky = new("err_sticky");
            this.err_sticky.configure(this, 1, 9, "RO", 1, 'h0, 0, 1, 0);
            this.irq_seen_sticky = new("irq_seen_sticky");
            this.irq_seen_sticky.configure(this, 1, 10, "RO", 1, 'h0, 0, 1, 0);
            this.fault_seen_sticky = new("fault_seen_sticky");
            this.fault_seen_sticky.configure(this, 1, 11, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__STATUS

    // reg - awr2243_control_csr::ERR_CODE_LIVE
    class awr2243_control_csr__ERR_CODE_LIVE extends uvm_reg;
        rand uvm_reg_field err_code_live;

        function new(string name = "awr2243_control_csr__ERR_CODE_LIVE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.err_code_live = new("err_code_live");
            this.err_code_live.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__ERR_CODE_LIVE

    // reg - awr2243_control_csr::ERR_CODE_STICKY
    class awr2243_control_csr__ERR_CODE_STICKY extends uvm_reg;
        rand uvm_reg_field err_code_sticky;

        function new(string name = "awr2243_control_csr__ERR_CODE_STICKY");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.err_code_sticky = new("err_code_sticky");
            this.err_code_sticky.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__ERR_CODE_STICKY

    // reg - awr2243_control_csr::STEP_ID_LIVE
    class awr2243_control_csr__STEP_ID_LIVE extends uvm_reg;
        rand uvm_reg_field step_id_live;

        function new(string name = "awr2243_control_csr__STEP_ID_LIVE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.step_id_live = new("step_id_live");
            this.step_id_live.configure(this, 8, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__STEP_ID_LIVE

    // reg - awr2243_control_csr::STEP_ID_SNAPSHOT
    class awr2243_control_csr__STEP_ID_SNAPSHOT extends uvm_reg;
        rand uvm_reg_field step_id_snapshot;

        function new(string name = "awr2243_control_csr__STEP_ID_SNAPSHOT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.step_id_snapshot = new("step_id_snapshot");
            this.step_id_snapshot.configure(this, 8, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__STEP_ID_SNAPSHOT

    // reg - awr2243_control_csr::LAST_OPCODE_LIVE
    class awr2243_control_csr__LAST_OPCODE_LIVE extends uvm_reg;
        rand uvm_reg_field last_opcode_live;

        function new(string name = "awr2243_control_csr__LAST_OPCODE_LIVE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.last_opcode_live = new("last_opcode_live");
            this.last_opcode_live.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__LAST_OPCODE_LIVE

    // reg - awr2243_control_csr::LAST_OPCODE_SNAP
    class awr2243_control_csr__LAST_OPCODE_SNAP extends uvm_reg;
        rand uvm_reg_field last_opcode_snap;

        function new(string name = "awr2243_control_csr__LAST_OPCODE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.last_opcode_snap = new("last_opcode_snap");
            this.last_opcode_snap.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__LAST_OPCODE_SNAP

    // reg - awr2243_control_csr::IRQ_COUNT
    class awr2243_control_csr__IRQ_COUNT extends uvm_reg;
        rand uvm_reg_field irq_count;

        function new(string name = "awr2243_control_csr__IRQ_COUNT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.irq_count = new("irq_count");
            this.irq_count.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__IRQ_COUNT

    // reg - awr2243_control_csr::FAULT_COUNT
    class awr2243_control_csr__FAULT_COUNT extends uvm_reg;
        rand uvm_reg_field fault_count;

        function new(string name = "awr2243_control_csr__FAULT_COUNT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.fault_count = new("fault_count");
            this.fault_count.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__FAULT_COUNT

    // reg - awr2243_control_csr::INIT_SCRIPT_ID
    class awr2243_control_csr__INIT_SCRIPT_ID extends uvm_reg;
        rand uvm_reg_field init_script_id;

        function new(string name = "awr2243_control_csr__INIT_SCRIPT_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.init_script_id = new("init_script_id");
            this.init_script_id.configure(this, 8, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__INIT_SCRIPT_ID

    // reg - awr2243_control_csr::RF_SCRIPT_ID
    class awr2243_control_csr__RF_SCRIPT_ID extends uvm_reg;
        rand uvm_reg_field rf_script_id;

        function new(string name = "awr2243_control_csr__RF_SCRIPT_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.rf_script_id = new("rf_script_id");
            this.rf_script_id.configure(this, 8, 0, "RW", 1, 'h1, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__RF_SCRIPT_ID

    // reg - awr2243_control_csr::PROFILE_SCRIPT_ID
    class awr2243_control_csr__PROFILE_SCRIPT_ID extends uvm_reg;
        rand uvm_reg_field profile_script_id;

        function new(string name = "awr2243_control_csr__PROFILE_SCRIPT_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.profile_script_id = new("profile_script_id");
            this.profile_script_id.configure(this, 8, 0, "RW", 1, 'h2, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__PROFILE_SCRIPT_ID

    // reg - awr2243_control_csr::FRAME_SCRIPT_ID
    class awr2243_control_csr__FRAME_SCRIPT_ID extends uvm_reg;
        rand uvm_reg_field frame_script_id;

        function new(string name = "awr2243_control_csr__FRAME_SCRIPT_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.frame_script_id = new("frame_script_id");
            this.frame_script_id.configure(this, 8, 0, "RW", 1, 'h3, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__FRAME_SCRIPT_ID

    // reg - awr2243_control_csr::MONITOR_SCRIPT_ID
    class awr2243_control_csr__MONITOR_SCRIPT_ID extends uvm_reg;
        rand uvm_reg_field monitor_script_id;

        function new(string name = "awr2243_control_csr__MONITOR_SCRIPT_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.monitor_script_id = new("monitor_script_id");
            this.monitor_script_id.configure(this, 8, 0, "RW", 1, 'h4, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__MONITOR_SCRIPT_ID

    // reg - awr2243_control_csr::START_SCRIPT_ID
    class awr2243_control_csr__START_SCRIPT_ID extends uvm_reg;
        rand uvm_reg_field start_script_id;

        function new(string name = "awr2243_control_csr__START_SCRIPT_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.start_script_id = new("start_script_id");
            this.start_script_id.configure(this, 8, 0, "RW", 1, 'h5, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__START_SCRIPT_ID

    // reg - awr2243_control_csr::STOP_SCRIPT_ID
    class awr2243_control_csr__STOP_SCRIPT_ID extends uvm_reg;
        rand uvm_reg_field stop_script_id;

        function new(string name = "awr2243_control_csr__STOP_SCRIPT_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.stop_script_id = new("stop_script_id");
            this.stop_script_id.configure(this, 8, 0, "RW", 1, 'h6, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__STOP_SCRIPT_ID

    // reg - awr2243_control_csr::SCRATCH
    class awr2243_control_csr__SCRATCH extends uvm_reg;
        rand uvm_reg_field scratch;

        function new(string name = "awr2243_control_csr__SCRATCH");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.scratch = new("scratch");
            this.scratch.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : awr2243_control_csr__SCRATCH

    // addrmap - awr2243_control_csr
    class awr2243_control_csr extends uvm_reg_block;
        rand awr2243_control_csr__VERSION VERSION;
        rand awr2243_control_csr__CONTROL CONTROL;
        rand awr2243_control_csr__STATUS STATUS;
        rand awr2243_control_csr__ERR_CODE_LIVE ERR_CODE_LIVE;
        rand awr2243_control_csr__ERR_CODE_STICKY ERR_CODE_STICKY;
        rand awr2243_control_csr__STEP_ID_LIVE STEP_ID_LIVE;
        rand awr2243_control_csr__STEP_ID_SNAPSHOT STEP_ID_SNAPSHOT;
        rand awr2243_control_csr__LAST_OPCODE_LIVE LAST_OPCODE_LIVE;
        rand awr2243_control_csr__LAST_OPCODE_SNAP LAST_OPCODE_SNAP;
        rand awr2243_control_csr__IRQ_COUNT IRQ_COUNT;
        rand awr2243_control_csr__FAULT_COUNT FAULT_COUNT;
        rand awr2243_control_csr__INIT_SCRIPT_ID INIT_SCRIPT_ID;
        rand awr2243_control_csr__RF_SCRIPT_ID RF_SCRIPT_ID;
        rand awr2243_control_csr__PROFILE_SCRIPT_ID PROFILE_SCRIPT_ID;
        rand awr2243_control_csr__FRAME_SCRIPT_ID FRAME_SCRIPT_ID;
        rand awr2243_control_csr__MONITOR_SCRIPT_ID MONITOR_SCRIPT_ID;
        rand awr2243_control_csr__START_SCRIPT_ID START_SCRIPT_ID;
        rand awr2243_control_csr__STOP_SCRIPT_ID STOP_SCRIPT_ID;
        rand awr2243_control_csr__SCRATCH SCRATCH;

        function new(string name = "awr2243_control_csr");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.VERSION = new("VERSION");
            this.VERSION.configure(this);

            this.VERSION.build();
            this.default_map.add_reg(this.VERSION, 'h0);
            this.CONTROL = new("CONTROL");
            this.CONTROL.configure(this);

            this.CONTROL.build();
            this.default_map.add_reg(this.CONTROL, 'h4);
            this.STATUS = new("STATUS");
            this.STATUS.configure(this);

            this.STATUS.build();
            this.default_map.add_reg(this.STATUS, 'h8);
            this.ERR_CODE_LIVE = new("ERR_CODE_LIVE");
            this.ERR_CODE_LIVE.configure(this);

            this.ERR_CODE_LIVE.build();
            this.default_map.add_reg(this.ERR_CODE_LIVE, 'hc);
            this.ERR_CODE_STICKY = new("ERR_CODE_STICKY");
            this.ERR_CODE_STICKY.configure(this);

            this.ERR_CODE_STICKY.build();
            this.default_map.add_reg(this.ERR_CODE_STICKY, 'h10);
            this.STEP_ID_LIVE = new("STEP_ID_LIVE");
            this.STEP_ID_LIVE.configure(this);

            this.STEP_ID_LIVE.build();
            this.default_map.add_reg(this.STEP_ID_LIVE, 'h14);
            this.STEP_ID_SNAPSHOT = new("STEP_ID_SNAPSHOT");
            this.STEP_ID_SNAPSHOT.configure(this);

            this.STEP_ID_SNAPSHOT.build();
            this.default_map.add_reg(this.STEP_ID_SNAPSHOT, 'h18);
            this.LAST_OPCODE_LIVE = new("LAST_OPCODE_LIVE");
            this.LAST_OPCODE_LIVE.configure(this);

            this.LAST_OPCODE_LIVE.build();
            this.default_map.add_reg(this.LAST_OPCODE_LIVE, 'h1c);
            this.LAST_OPCODE_SNAP = new("LAST_OPCODE_SNAP");
            this.LAST_OPCODE_SNAP.configure(this);

            this.LAST_OPCODE_SNAP.build();
            this.default_map.add_reg(this.LAST_OPCODE_SNAP, 'h20);
            this.IRQ_COUNT = new("IRQ_COUNT");
            this.IRQ_COUNT.configure(this);

            this.IRQ_COUNT.build();
            this.default_map.add_reg(this.IRQ_COUNT, 'h24);
            this.FAULT_COUNT = new("FAULT_COUNT");
            this.FAULT_COUNT.configure(this);

            this.FAULT_COUNT.build();
            this.default_map.add_reg(this.FAULT_COUNT, 'h28);
            this.INIT_SCRIPT_ID = new("INIT_SCRIPT_ID");
            this.INIT_SCRIPT_ID.configure(this);

            this.INIT_SCRIPT_ID.build();
            this.default_map.add_reg(this.INIT_SCRIPT_ID, 'h2c);
            this.RF_SCRIPT_ID = new("RF_SCRIPT_ID");
            this.RF_SCRIPT_ID.configure(this);

            this.RF_SCRIPT_ID.build();
            this.default_map.add_reg(this.RF_SCRIPT_ID, 'h30);
            this.PROFILE_SCRIPT_ID = new("PROFILE_SCRIPT_ID");
            this.PROFILE_SCRIPT_ID.configure(this);

            this.PROFILE_SCRIPT_ID.build();
            this.default_map.add_reg(this.PROFILE_SCRIPT_ID, 'h34);
            this.FRAME_SCRIPT_ID = new("FRAME_SCRIPT_ID");
            this.FRAME_SCRIPT_ID.configure(this);

            this.FRAME_SCRIPT_ID.build();
            this.default_map.add_reg(this.FRAME_SCRIPT_ID, 'h38);
            this.MONITOR_SCRIPT_ID = new("MONITOR_SCRIPT_ID");
            this.MONITOR_SCRIPT_ID.configure(this);

            this.MONITOR_SCRIPT_ID.build();
            this.default_map.add_reg(this.MONITOR_SCRIPT_ID, 'h3c);
            this.START_SCRIPT_ID = new("START_SCRIPT_ID");
            this.START_SCRIPT_ID.configure(this);

            this.START_SCRIPT_ID.build();
            this.default_map.add_reg(this.START_SCRIPT_ID, 'h40);
            this.STOP_SCRIPT_ID = new("STOP_SCRIPT_ID");
            this.STOP_SCRIPT_ID.configure(this);

            this.STOP_SCRIPT_ID.build();
            this.default_map.add_reg(this.STOP_SCRIPT_ID, 'h44);
            this.SCRATCH = new("SCRATCH");
            this.SCRATCH.configure(this);

            this.SCRATCH.build();
            this.default_map.add_reg(this.SCRATCH, 'h48);
        endfunction : build
    endclass : awr2243_control_csr

endpackage: awr2243_control_csr_ral_pkg
