
// This file was autogenerated by PeakRDL-uvm
package ddr_ringbuffer_controller_csr_ral_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - ddr_ringbuffer_controller_csr::CTRL
    class ddr_ringbuffer_controller_csr__CTRL extends uvm_reg;
        rand uvm_reg_field enable;
        rand uvm_reg_field allow_overwrite;
        rand uvm_reg_field drop_invalid_slot;
        rand uvm_reg_field drop_on_no_space;

        function new(string name = "ddr_ringbuffer_controller_csr__CTRL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.allow_overwrite = new("allow_overwrite");
            this.allow_overwrite.configure(this, 1, 1, "RW", 1, 'h0, 1, 1, 0);
            this.drop_invalid_slot = new("drop_invalid_slot");
            this.drop_invalid_slot.configure(this, 1, 2, "RW", 1, 'h1, 1, 1, 0);
            this.drop_on_no_space = new("drop_on_no_space");
            this.drop_on_no_space.configure(this, 1, 3, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__CTRL

    // reg - ddr_ringbuffer_controller_csr::STATUS
    class ddr_ringbuffer_controller_csr__STATUS extends uvm_reg;
        rand uvm_reg_field full;
        rand uvm_reg_field almost_full;
        rand uvm_reg_field empty;
        rand uvm_reg_field rd_busy;
        rand uvm_reg_field err_cfg_align;
        rand uvm_reg_field err_no_space;
        rand uvm_reg_field err_slot_proto;
        rand uvm_reg_field err_slot_too_large;
        rand uvm_reg_field err_axi_wr_resp;
        rand uvm_reg_field err_axi_rd_resp;
        rand uvm_reg_field err_illegal_read;

        function new(string name = "ddr_ringbuffer_controller_csr__STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.full = new("full");
            this.full.configure(this, 1, 0, "RO", 1, 'h0, 0, 1, 0);
            this.almost_full = new("almost_full");
            this.almost_full.configure(this, 1, 1, "RO", 1, 'h0, 0, 1, 0);
            this.empty = new("empty");
            this.empty.configure(this, 1, 2, "RO", 1, 'h0, 0, 1, 0);
            this.rd_busy = new("rd_busy");
            this.rd_busy.configure(this, 1, 3, "RO", 1, 'h0, 0, 1, 0);
            this.err_cfg_align = new("err_cfg_align");
            this.err_cfg_align.configure(this, 1, 8, "RO", 1, 'h0, 0, 1, 0);
            this.err_no_space = new("err_no_space");
            this.err_no_space.configure(this, 1, 9, "RO", 1, 'h0, 0, 1, 0);
            this.err_slot_proto = new("err_slot_proto");
            this.err_slot_proto.configure(this, 1, 10, "RO", 1, 'h0, 0, 1, 0);
            this.err_slot_too_large = new("err_slot_too_large");
            this.err_slot_too_large.configure(this, 1, 11, "RO", 1, 'h0, 0, 1, 0);
            this.err_axi_wr_resp = new("err_axi_wr_resp");
            this.err_axi_wr_resp.configure(this, 1, 12, "RO", 1, 'h0, 0, 1, 0);
            this.err_axi_rd_resp = new("err_axi_rd_resp");
            this.err_axi_rd_resp.configure(this, 1, 13, "RO", 1, 'h0, 0, 1, 0);
            this.err_illegal_read = new("err_illegal_read");
            this.err_illegal_read.configure(this, 1, 14, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__STATUS

    // reg - ddr_ringbuffer_controller_csr::RING_BASE_LO
    class ddr_ringbuffer_controller_csr__RING_BASE_LO extends uvm_reg;
        rand uvm_reg_field ring_base_lo;

        function new(string name = "ddr_ringbuffer_controller_csr__RING_BASE_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ring_base_lo = new("ring_base_lo");
            this.ring_base_lo.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__RING_BASE_LO

    // reg - ddr_ringbuffer_controller_csr::RING_BASE_HI
    class ddr_ringbuffer_controller_csr__RING_BASE_HI extends uvm_reg;
        rand uvm_reg_field ring_base_hi;

        function new(string name = "ddr_ringbuffer_controller_csr__RING_BASE_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ring_base_hi = new("ring_base_hi");
            this.ring_base_hi.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__RING_BASE_HI

    // reg - ddr_ringbuffer_controller_csr::RING_SIZE_BYTES
    class ddr_ringbuffer_controller_csr__RING_SIZE_BYTES extends uvm_reg;
        rand uvm_reg_field ring_size_bytes;

        function new(string name = "ddr_ringbuffer_controller_csr__RING_SIZE_BYTES");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ring_size_bytes = new("ring_size_bytes");
            this.ring_size_bytes.configure(this, 32, 0, "RW", 1, 'h10000, 1, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__RING_SIZE_BYTES

    // reg - ddr_ringbuffer_controller_csr::READ_CMD
    class ddr_ringbuffer_controller_csr__READ_CMD extends uvm_reg;
        rand uvm_reg_field issue_head_read;
        rand uvm_reg_field consume_head;

        function new(string name = "ddr_ringbuffer_controller_csr__READ_CMD");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.issue_head_read = new("issue_head_read");
            this.issue_head_read.configure(this, 1, 0, "WO", 1, 'h0, 1, 1, 0);
            this.consume_head = new("consume_head");
            this.consume_head.configure(this, 1, 1, "WO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__READ_CMD

    // reg - ddr_ringbuffer_controller_csr::USED_BYTES
    class ddr_ringbuffer_controller_csr__USED_BYTES extends uvm_reg;
        rand uvm_reg_field used_bytes;

        function new(string name = "ddr_ringbuffer_controller_csr__USED_BYTES");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.used_bytes = new("used_bytes");
            this.used_bytes.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__USED_BYTES

    // reg - ddr_ringbuffer_controller_csr::FREE_BYTES
    class ddr_ringbuffer_controller_csr__FREE_BYTES extends uvm_reg;
        rand uvm_reg_field free_bytes;

        function new(string name = "ddr_ringbuffer_controller_csr__FREE_BYTES");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.free_bytes = new("free_bytes");
            this.free_bytes.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__FREE_BYTES

    // reg - ddr_ringbuffer_controller_csr::COMMITTED_BYTES
    class ddr_ringbuffer_controller_csr__COMMITTED_BYTES extends uvm_reg;
        rand uvm_reg_field committed_bytes;

        function new(string name = "ddr_ringbuffer_controller_csr__COMMITTED_BYTES");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.committed_bytes = new("committed_bytes");
            this.committed_bytes.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__COMMITTED_BYTES

    // reg - ddr_ringbuffer_controller_csr::WR_PTR_LO
    class ddr_ringbuffer_controller_csr__WR_PTR_LO extends uvm_reg;
        rand uvm_reg_field wr_ptr_lo;

        function new(string name = "ddr_ringbuffer_controller_csr__WR_PTR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.wr_ptr_lo = new("wr_ptr_lo");
            this.wr_ptr_lo.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__WR_PTR_LO

    // reg - ddr_ringbuffer_controller_csr::WR_PTR_HI
    class ddr_ringbuffer_controller_csr__WR_PTR_HI extends uvm_reg;
        rand uvm_reg_field wr_ptr_hi;

        function new(string name = "ddr_ringbuffer_controller_csr__WR_PTR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.wr_ptr_hi = new("wr_ptr_hi");
            this.wr_ptr_hi.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__WR_PTR_HI

    // reg - ddr_ringbuffer_controller_csr::RD_PTR_LO
    class ddr_ringbuffer_controller_csr__RD_PTR_LO extends uvm_reg;
        rand uvm_reg_field rd_ptr_lo;

        function new(string name = "ddr_ringbuffer_controller_csr__RD_PTR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.rd_ptr_lo = new("rd_ptr_lo");
            this.rd_ptr_lo.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__RD_PTR_LO

    // reg - ddr_ringbuffer_controller_csr::RD_PTR_HI
    class ddr_ringbuffer_controller_csr__RD_PTR_HI extends uvm_reg;
        rand uvm_reg_field rd_ptr_hi;

        function new(string name = "ddr_ringbuffer_controller_csr__RD_PTR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.rd_ptr_hi = new("rd_ptr_hi");
            this.rd_ptr_hi.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__RD_PTR_HI

    // reg - ddr_ringbuffer_controller_csr::COMMIT_PTR_LO
    class ddr_ringbuffer_controller_csr__COMMIT_PTR_LO extends uvm_reg;
        rand uvm_reg_field commit_ptr_lo;

        function new(string name = "ddr_ringbuffer_controller_csr__COMMIT_PTR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.commit_ptr_lo = new("commit_ptr_lo");
            this.commit_ptr_lo.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__COMMIT_PTR_LO

    // reg - ddr_ringbuffer_controller_csr::COMMIT_PTR_HI
    class ddr_ringbuffer_controller_csr__COMMIT_PTR_HI extends uvm_reg;
        rand uvm_reg_field commit_ptr_hi;

        function new(string name = "ddr_ringbuffer_controller_csr__COMMIT_PTR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.commit_ptr_hi = new("commit_ptr_hi");
            this.commit_ptr_hi.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__COMMIT_PTR_HI

    // reg - ddr_ringbuffer_controller_csr::WRAP_COUNT
    class ddr_ringbuffer_controller_csr__WRAP_COUNT extends uvm_reg;
        rand uvm_reg_field wrap_count;

        function new(string name = "ddr_ringbuffer_controller_csr__WRAP_COUNT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.wrap_count = new("wrap_count");
            this.wrap_count.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__WRAP_COUNT

    // reg - ddr_ringbuffer_controller_csr::OVERFLOW_COUNT
    class ddr_ringbuffer_controller_csr__OVERFLOW_COUNT extends uvm_reg;
        rand uvm_reg_field overflow_count;

        function new(string name = "ddr_ringbuffer_controller_csr__OVERFLOW_COUNT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.overflow_count = new("overflow_count");
            this.overflow_count.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__OVERFLOW_COUNT

    // reg - ddr_ringbuffer_controller_csr::DROP_COUNT
    class ddr_ringbuffer_controller_csr__DROP_COUNT extends uvm_reg;
        rand uvm_reg_field drop_count;

        function new(string name = "ddr_ringbuffer_controller_csr__DROP_COUNT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.drop_count = new("drop_count");
            this.drop_count.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__DROP_COUNT

    // reg - ddr_ringbuffer_controller_csr::LAST_COMMIT_ADDR_LO
    class ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_LO extends uvm_reg;
        rand uvm_reg_field slot_addr_lo;

        function new(string name = "ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_addr_lo = new("slot_addr_lo");
            this.slot_addr_lo.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_LO

    // reg - ddr_ringbuffer_controller_csr::LAST_COMMIT_ADDR_HI
    class ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_HI extends uvm_reg;
        rand uvm_reg_field slot_addr_hi;

        function new(string name = "ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_addr_hi = new("slot_addr_hi");
            this.slot_addr_hi.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_HI

    // reg - ddr_ringbuffer_controller_csr::LAST_COMMIT_INFO
    class ddr_ringbuffer_controller_csr__LAST_COMMIT_INFO extends uvm_reg;
        rand uvm_reg_field slot_bytes;
        rand uvm_reg_field valid_good;
        rand uvm_reg_field overflow_err;
        rand uvm_reg_field commit_valid;

        function new(string name = "ddr_ringbuffer_controller_csr__LAST_COMMIT_INFO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_bytes = new("slot_bytes");
            this.slot_bytes.configure(this, 24, 0, "RO", 1, 'h0, 0, 1, 0);
            this.valid_good = new("valid_good");
            this.valid_good.configure(this, 1, 24, "RO", 1, 'h0, 0, 1, 0);
            this.overflow_err = new("overflow_err");
            this.overflow_err.configure(this, 1, 25, "RO", 1, 'h0, 0, 1, 0);
            this.commit_valid = new("commit_valid");
            this.commit_valid.configure(this, 1, 31, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__LAST_COMMIT_INFO

    // reg - ddr_ringbuffer_controller_csr::LAST_COMMIT_SEQ
    class ddr_ringbuffer_controller_csr__LAST_COMMIT_SEQ extends uvm_reg;
        rand uvm_reg_field slot_seq;

        function new(string name = "ddr_ringbuffer_controller_csr__LAST_COMMIT_SEQ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_seq = new("slot_seq");
            this.slot_seq.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__LAST_COMMIT_SEQ

    // reg - ddr_ringbuffer_controller_csr::HEAD_DESC_ADDR_LO
    class ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_LO extends uvm_reg;
        rand uvm_reg_field slot_addr_lo;

        function new(string name = "ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_addr_lo = new("slot_addr_lo");
            this.slot_addr_lo.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_LO

    // reg - ddr_ringbuffer_controller_csr::HEAD_DESC_ADDR_HI
    class ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_HI extends uvm_reg;
        rand uvm_reg_field slot_addr_hi;

        function new(string name = "ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_addr_hi = new("slot_addr_hi");
            this.slot_addr_hi.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_HI

    // reg - ddr_ringbuffer_controller_csr::HEAD_DESC_INFO
    class ddr_ringbuffer_controller_csr__HEAD_DESC_INFO extends uvm_reg;
        rand uvm_reg_field slot_bytes;
        rand uvm_reg_field valid_good;
        rand uvm_reg_field overflow_err;
        rand uvm_reg_field desc_valid;

        function new(string name = "ddr_ringbuffer_controller_csr__HEAD_DESC_INFO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_bytes = new("slot_bytes");
            this.slot_bytes.configure(this, 24, 0, "RO", 1, 'h0, 0, 1, 0);
            this.valid_good = new("valid_good");
            this.valid_good.configure(this, 1, 24, "RO", 1, 'h0, 0, 1, 0);
            this.overflow_err = new("overflow_err");
            this.overflow_err.configure(this, 1, 25, "RO", 1, 'h0, 0, 1, 0);
            this.desc_valid = new("desc_valid");
            this.desc_valid.configure(this, 1, 31, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__HEAD_DESC_INFO

    // reg - ddr_ringbuffer_controller_csr::HEAD_DESC_SEQ
    class ddr_ringbuffer_controller_csr__HEAD_DESC_SEQ extends uvm_reg;
        rand uvm_reg_field slot_seq;

        function new(string name = "ddr_ringbuffer_controller_csr__HEAD_DESC_SEQ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_seq = new("slot_seq");
            this.slot_seq.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr__HEAD_DESC_SEQ

    // addrmap - ddr_ringbuffer_controller_csr
    class ddr_ringbuffer_controller_csr extends uvm_reg_block;
        rand ddr_ringbuffer_controller_csr__CTRL CTRL;
        rand ddr_ringbuffer_controller_csr__STATUS STATUS;
        rand ddr_ringbuffer_controller_csr__RING_BASE_LO RING_BASE_LO;
        rand ddr_ringbuffer_controller_csr__RING_BASE_HI RING_BASE_HI;
        rand ddr_ringbuffer_controller_csr__RING_SIZE_BYTES RING_SIZE_BYTES;
        rand ddr_ringbuffer_controller_csr__READ_CMD READ_CMD;
        rand ddr_ringbuffer_controller_csr__USED_BYTES USED_BYTES;
        rand ddr_ringbuffer_controller_csr__FREE_BYTES FREE_BYTES;
        rand ddr_ringbuffer_controller_csr__COMMITTED_BYTES COMMITTED_BYTES;
        rand ddr_ringbuffer_controller_csr__WR_PTR_LO WR_PTR_LO;
        rand ddr_ringbuffer_controller_csr__WR_PTR_HI WR_PTR_HI;
        rand ddr_ringbuffer_controller_csr__RD_PTR_LO RD_PTR_LO;
        rand ddr_ringbuffer_controller_csr__RD_PTR_HI RD_PTR_HI;
        rand ddr_ringbuffer_controller_csr__COMMIT_PTR_LO COMMIT_PTR_LO;
        rand ddr_ringbuffer_controller_csr__COMMIT_PTR_HI COMMIT_PTR_HI;
        rand ddr_ringbuffer_controller_csr__WRAP_COUNT WRAP_COUNT;
        rand ddr_ringbuffer_controller_csr__OVERFLOW_COUNT OVERFLOW_COUNT;
        rand ddr_ringbuffer_controller_csr__DROP_COUNT DROP_COUNT;
        rand ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_LO LAST_COMMIT_ADDR_LO;
        rand ddr_ringbuffer_controller_csr__LAST_COMMIT_ADDR_HI LAST_COMMIT_ADDR_HI;
        rand ddr_ringbuffer_controller_csr__LAST_COMMIT_INFO LAST_COMMIT_INFO;
        rand ddr_ringbuffer_controller_csr__LAST_COMMIT_SEQ LAST_COMMIT_SEQ;
        rand ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_LO HEAD_DESC_ADDR_LO;
        rand ddr_ringbuffer_controller_csr__HEAD_DESC_ADDR_HI HEAD_DESC_ADDR_HI;
        rand ddr_ringbuffer_controller_csr__HEAD_DESC_INFO HEAD_DESC_INFO;
        rand ddr_ringbuffer_controller_csr__HEAD_DESC_SEQ HEAD_DESC_SEQ;

        function new(string name = "ddr_ringbuffer_controller_csr");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.CTRL = new("CTRL");
            this.CTRL.configure(this);

            this.CTRL.build();
            this.default_map.add_reg(this.CTRL, 'h0);
            this.STATUS = new("STATUS");
            this.STATUS.configure(this);

            this.STATUS.build();
            this.default_map.add_reg(this.STATUS, 'h4);
            this.RING_BASE_LO = new("RING_BASE_LO");
            this.RING_BASE_LO.configure(this);

            this.RING_BASE_LO.build();
            this.default_map.add_reg(this.RING_BASE_LO, 'h8);
            this.RING_BASE_HI = new("RING_BASE_HI");
            this.RING_BASE_HI.configure(this);

            this.RING_BASE_HI.build();
            this.default_map.add_reg(this.RING_BASE_HI, 'hc);
            this.RING_SIZE_BYTES = new("RING_SIZE_BYTES");
            this.RING_SIZE_BYTES.configure(this);

            this.RING_SIZE_BYTES.build();
            this.default_map.add_reg(this.RING_SIZE_BYTES, 'h10);
            this.READ_CMD = new("READ_CMD");
            this.READ_CMD.configure(this);

            this.READ_CMD.build();
            this.default_map.add_reg(this.READ_CMD, 'h14);
            this.USED_BYTES = new("USED_BYTES");
            this.USED_BYTES.configure(this);

            this.USED_BYTES.build();
            this.default_map.add_reg(this.USED_BYTES, 'h20);
            this.FREE_BYTES = new("FREE_BYTES");
            this.FREE_BYTES.configure(this);

            this.FREE_BYTES.build();
            this.default_map.add_reg(this.FREE_BYTES, 'h24);
            this.COMMITTED_BYTES = new("COMMITTED_BYTES");
            this.COMMITTED_BYTES.configure(this);

            this.COMMITTED_BYTES.build();
            this.default_map.add_reg(this.COMMITTED_BYTES, 'h28);
            this.WR_PTR_LO = new("WR_PTR_LO");
            this.WR_PTR_LO.configure(this);

            this.WR_PTR_LO.build();
            this.default_map.add_reg(this.WR_PTR_LO, 'h30);
            this.WR_PTR_HI = new("WR_PTR_HI");
            this.WR_PTR_HI.configure(this);

            this.WR_PTR_HI.build();
            this.default_map.add_reg(this.WR_PTR_HI, 'h34);
            this.RD_PTR_LO = new("RD_PTR_LO");
            this.RD_PTR_LO.configure(this);

            this.RD_PTR_LO.build();
            this.default_map.add_reg(this.RD_PTR_LO, 'h38);
            this.RD_PTR_HI = new("RD_PTR_HI");
            this.RD_PTR_HI.configure(this);

            this.RD_PTR_HI.build();
            this.default_map.add_reg(this.RD_PTR_HI, 'h3c);
            this.COMMIT_PTR_LO = new("COMMIT_PTR_LO");
            this.COMMIT_PTR_LO.configure(this);

            this.COMMIT_PTR_LO.build();
            this.default_map.add_reg(this.COMMIT_PTR_LO, 'h40);
            this.COMMIT_PTR_HI = new("COMMIT_PTR_HI");
            this.COMMIT_PTR_HI.configure(this);

            this.COMMIT_PTR_HI.build();
            this.default_map.add_reg(this.COMMIT_PTR_HI, 'h44);
            this.WRAP_COUNT = new("WRAP_COUNT");
            this.WRAP_COUNT.configure(this);

            this.WRAP_COUNT.build();
            this.default_map.add_reg(this.WRAP_COUNT, 'h48);
            this.OVERFLOW_COUNT = new("OVERFLOW_COUNT");
            this.OVERFLOW_COUNT.configure(this);

            this.OVERFLOW_COUNT.build();
            this.default_map.add_reg(this.OVERFLOW_COUNT, 'h4c);
            this.DROP_COUNT = new("DROP_COUNT");
            this.DROP_COUNT.configure(this);

            this.DROP_COUNT.build();
            this.default_map.add_reg(this.DROP_COUNT, 'h50);
            this.LAST_COMMIT_ADDR_LO = new("LAST_COMMIT_ADDR_LO");
            this.LAST_COMMIT_ADDR_LO.configure(this);

            this.LAST_COMMIT_ADDR_LO.build();
            this.default_map.add_reg(this.LAST_COMMIT_ADDR_LO, 'h60);
            this.LAST_COMMIT_ADDR_HI = new("LAST_COMMIT_ADDR_HI");
            this.LAST_COMMIT_ADDR_HI.configure(this);

            this.LAST_COMMIT_ADDR_HI.build();
            this.default_map.add_reg(this.LAST_COMMIT_ADDR_HI, 'h64);
            this.LAST_COMMIT_INFO = new("LAST_COMMIT_INFO");
            this.LAST_COMMIT_INFO.configure(this);

            this.LAST_COMMIT_INFO.build();
            this.default_map.add_reg(this.LAST_COMMIT_INFO, 'h68);
            this.LAST_COMMIT_SEQ = new("LAST_COMMIT_SEQ");
            this.LAST_COMMIT_SEQ.configure(this);

            this.LAST_COMMIT_SEQ.build();
            this.default_map.add_reg(this.LAST_COMMIT_SEQ, 'h6c);
            this.HEAD_DESC_ADDR_LO = new("HEAD_DESC_ADDR_LO");
            this.HEAD_DESC_ADDR_LO.configure(this);

            this.HEAD_DESC_ADDR_LO.build();
            this.default_map.add_reg(this.HEAD_DESC_ADDR_LO, 'h80);
            this.HEAD_DESC_ADDR_HI = new("HEAD_DESC_ADDR_HI");
            this.HEAD_DESC_ADDR_HI.configure(this);

            this.HEAD_DESC_ADDR_HI.build();
            this.default_map.add_reg(this.HEAD_DESC_ADDR_HI, 'h84);
            this.HEAD_DESC_INFO = new("HEAD_DESC_INFO");
            this.HEAD_DESC_INFO.configure(this);

            this.HEAD_DESC_INFO.build();
            this.default_map.add_reg(this.HEAD_DESC_INFO, 'h88);
            this.HEAD_DESC_SEQ = new("HEAD_DESC_SEQ");
            this.HEAD_DESC_SEQ.configure(this);

            this.HEAD_DESC_SEQ.build();
            this.default_map.add_reg(this.HEAD_DESC_SEQ, 'h8c);
        endfunction : build
    endclass : ddr_ringbuffer_controller_csr

endpackage: ddr_ringbuffer_controller_csr_ral_pkg
