# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/fpga/xilinxfpga/awr2243-fpga-capture/vivado_project/vivado_ku5p/awr2243_fpga_capture.runs/synth_1/awr2243_capture_top_exec.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku5p-ffvb676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/fpga/xilinxfpga/awr2243-fpga-capture/vivado_project/vivado_ku5p/awr2243_fpga_capture.cache/wt [current_project]
set_property parent.project_path E:/fpga/xilinxfpga/awr2243-fpga-capture/vivado_project/vivado_ku5p/awr2243_fpga_capture.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/fpga/xilinxfpga/awr2243-fpga-capture/vivado_project/vivado_ku5p/awr2243_fpga_capture.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/slot_packer_macros.svh
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/ddr_ringbuffer_macros.svh
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/csi_packet_extractor_macros.svh
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/awr2243_script_macros.svh
}
set_property file_type "Verilog Header" [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/slot_packer_macros.svh]
set_property is_global_include true [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/slot_packer_macros.svh]
set_property file_type "Verilog Header" [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/ddr_ringbuffer_macros.svh]
set_property is_global_include true [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/ddr_ringbuffer_macros.svh]
set_property file_type "Verilog Header" [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/csi_packet_extractor_macros.svh]
set_property is_global_include true [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/csi_packet_extractor_macros.svh]
set_property file_type "Verilog Header" [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/awr2243_script_macros.svh]
set_property is_global_include true [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/include/awr2243_script_macros.svh]
read_verilog -library xil_defaultlib -sv {
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_cfg_sequencer.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/pkg/awr2243_script_pkg.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_cmd_decode.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_cmd_fetch.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/generated/awr2243_control_csr_pkg.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/generated/awr2243_control_csr.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_ctrl_top.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_reset_ctrl.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_script_ram.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_status_mon.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/awr2243_timer.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/if/axi4_lite_if.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/if/axi4_mm_if.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/pkg/ddr_ringbuffer_pkg.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/axil/axil_bar0_decode.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/if/axis_stream_if.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/pkg/csi_packet_pkg.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/csi_packet_extractor.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/ddr_ringbuffer_controller.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/generated/ddr_ringbuffer_controller_csr_pkg.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/ddr_ringbuffer_controller_axil.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/generated/ddr_ringbuffer_controller_csr.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/pkg/slot_packer_pkg.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/fixed_slot_packer.sv
  E:/fpga/xilinxfpga/awr2243-fpga-capture/rtl/core/spi_master_engine.sv
  C:/Users/admin/Downloads/awr2243_capture_top_exec.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/fpga/xilinxfpga/awr2243-fpga-capture/constraints/awr2243_project_stub.xdc
set_property used_in_implementation false [get_files E:/fpga/xilinxfpga/awr2243-fpga-capture/constraints/awr2243_project_stub.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top awr2243_capture_top_exec -part xcku5p-ffvb676-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef awr2243_capture_top_exec.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file awr2243_capture_top_exec_utilization_synth.rpt -pb awr2243_capture_top_exec_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
