module awr2243_cmd_decode_cocotb_top #(
    parameter int unsigned WORD_W        = 64,
    parameter int unsigned PC_W          = awr2243_script_pkg::clog2_safe(32),
    parameter int unsigned STEP_ID_W     = 16,
    parameter int unsigned ERR_CODE_W    = 8,
    parameter int unsigned TIMER_VALUE_W = 32,
    parameter int unsigned TIMER_UNIT_W  = 2
) (
    input logic clk_i,
    input logic rst_ni,

    input logic              cmd_valid_i,
    input logic [WORD_W-1:0] cmd_word_i,
    input logic [  PC_W-1:0] pc_i,

    output logic                  fetch_advance_o,
    output logic                  fetch_hold_o,
    output logic                  jump_en_o,
    output logic [      PC_W-1:0] jump_addr_o,
    output logic                  cmd_done_o,
    output logic                  cmd_error_o,
    output logic [ERR_CODE_W-1:0] error_code_o,
    output logic [ STEP_ID_W-1:0] step_id_o,
    output logic [           7:0] last_opcode_o,
    output logic                  busy_o,
    output logic [           3:0] state_o,

    output logic        spi_cmd_valid_o,
    input  logic        spi_cmd_ready_i,
    output logic        spi_cmd_is_read_o,
    output logic [15:0] spi_cmd_word_o,
    input  logic        spi_rsp_valid_i,
    input  logic [15:0] spi_rsp_word_i,
    input  logic        spi_busy_i,
    input  logic        spi_done_i,
    input  logic        spi_timeout_i,

    output logic                     timer_start_o,
    output logic                     timer_clear_o,
    output logic [TIMER_VALUE_W-1:0] timer_period_value_o,
    output logic [ TIMER_UNIT_W-1:0] timer_period_unit_o,
    input  logic                     timer_busy_i,
    input  logic                     timer_done_i,
    input  logic                     timer_expired_i,

    output logic clr_irq_sticky_o,
    output logic clr_fault_sticky_o,
    input  logic host_irq_rise_i,
    input  logic host_irq_sticky_i,
    input  logic fault_active_i,
    input  logic fault_sticky_i
);

  awr2243_cmd_decode #(
      .WORD_W       (WORD_W),
      .PC_W         (PC_W),
      .STEP_ID_W    (STEP_ID_W),
      .ERR_CODE_W   (ERR_CODE_W),
      .TIMER_VALUE_W(TIMER_VALUE_W),
      .TIMER_UNIT_W (TIMER_UNIT_W)
  ) dut (
      .clk_i               (clk_i),
      .rst_ni              (rst_ni),
      .cmd_valid_i         (cmd_valid_i),
      .cmd_word_i          (cmd_word_i),
      .pc_i                (pc_i),
      .fetch_advance_o     (fetch_advance_o),
      .fetch_hold_o        (fetch_hold_o),
      .jump_en_o           (jump_en_o),
      .jump_addr_o         (jump_addr_o),
      .cmd_done_o          (cmd_done_o),
      .cmd_error_o         (cmd_error_o),
      .error_code_o        (error_code_o),
      .step_id_o           (step_id_o),
      .last_opcode_o       (last_opcode_o),
      .busy_o              (busy_o),
      .state_o             (state_o),
      .spi_cmd_valid_o     (spi_cmd_valid_o),
      .spi_cmd_ready_i     (spi_cmd_ready_i),
      .spi_cmd_is_read_o   (spi_cmd_is_read_o),
      .spi_cmd_word_o      (spi_cmd_word_o),
      .spi_rsp_valid_i     (spi_rsp_valid_i),
      .spi_rsp_word_i      (spi_rsp_word_i),
      .spi_busy_i          (spi_busy_i),
      .spi_done_i          (spi_done_i),
      .spi_timeout_i       (spi_timeout_i),
      .timer_start_o       (timer_start_o),
      .timer_clear_o       (timer_clear_o),
      .timer_period_value_o(timer_period_value_o),
      .timer_period_unit_o (timer_period_unit_o),
      .timer_busy_i        (timer_busy_i),
      .timer_done_i        (timer_done_i),
      .timer_expired_i     (timer_expired_i),
      .clr_irq_sticky_o    (clr_irq_sticky_o),
      .clr_fault_sticky_o  (clr_fault_sticky_o),
      .host_irq_rise_i     (host_irq_rise_i),
      .host_irq_sticky_i   (host_irq_sticky_i),
      .fault_active_i      (fault_active_i),
      .fault_sticky_i      (fault_sticky_i)
  );

endmodule
