`timescale 1ns / 1ps

module awr2243_capture_core_impl #(
    parameter int unsigned AXIS_DATA_W = 256,
    parameter int unsigned AXIS_USER_W = 64,
    parameter int unsigned AXIL_ADDR_W = 32,
    parameter int unsigned AXIL_DATA_W = 32,
    parameter int unsigned AXI_ADDR_W  = 34,
    parameter int unsigned AXI_DATA_W  = 256
) (
    input  logic axi_clk,
    input  logic axi_rst_n,

    input  logic [AXIS_DATA_W-1:0]   s_axis_csi_tdata,
    input  logic [AXIS_DATA_W/8-1:0] s_axis_csi_tkeep,
    input  logic                     s_axis_csi_tvalid,
    output logic                     s_axis_csi_tready,
    input  logic                     s_axis_csi_tlast,
    input  logic [AXIS_USER_W-1:0]   s_axis_csi_tuser,

    input  logic [AXIL_ADDR_W-1:0]   s_axil_bar0_awaddr,
    input  logic [2:0]               s_axil_bar0_awprot,
    input  logic                     s_axil_bar0_awvalid,
    output logic                     s_axil_bar0_awready,
    input  logic [AXIL_DATA_W-1:0]   s_axil_bar0_wdata,
    input  logic [AXIL_DATA_W/8-1:0] s_axil_bar0_wstrb,
    input  logic                     s_axil_bar0_wvalid,
    output logic                     s_axil_bar0_wready,
    output logic [1:0]               s_axil_bar0_bresp,
    output logic                     s_axil_bar0_bvalid,
    input  logic                     s_axil_bar0_bready,
    input  logic [AXIL_ADDR_W-1:0]   s_axil_bar0_araddr,
    input  logic [2:0]               s_axil_bar0_arprot,
    input  logic                     s_axil_bar0_arvalid,
    output logic                     s_axil_bar0_arready,
    output logic [AXIL_DATA_W-1:0]   s_axil_bar0_rdata,
    output logic [1:0]               s_axil_bar0_rresp,
    output logic                     s_axil_bar0_rvalid,
    input  logic                     s_axil_bar0_rready,

    output logic [AXI_ADDR_W-1:0]    m_axi_awaddr,
    output logic [7:0]               m_axi_awlen,
    output logic [2:0]               m_axi_awsize,
    output logic [1:0]               m_axi_awburst,
    output logic                     m_axi_awvalid,
    input  logic                     m_axi_awready,
    output logic [AXI_DATA_W-1:0]    m_axi_wdata,
    output logic [AXI_DATA_W/8-1:0]  m_axi_wstrb,
    output logic                     m_axi_wlast,
    output logic                     m_axi_wvalid,
    input  logic                     m_axi_wready,
    input  logic [1:0]               m_axi_bresp,
    input  logic                     m_axi_bvalid,
    output logic                     m_axi_bready,
    output logic [AXI_ADDR_W-1:0]    m_axi_araddr,
    output logic [7:0]               m_axi_arlen,
    output logic [2:0]               m_axi_arsize,
    output logic [1:0]               m_axi_arburst,
    output logic                     m_axi_arvalid,
    input  logic                     m_axi_arready,
    input  logic [AXI_DATA_W-1:0]    m_axi_rdata,
    input  logic [1:0]               m_axi_rresp,
    input  logic                     m_axi_rlast,
    input  logic                     m_axi_rvalid,
    output logic                     m_axi_rready,

    output logic spi_sclk_o,
    output logic spi_cs_n_o,
    output logic spi_mosi_o,
    input  logic spi_miso_i,
    output logic sop0_o,
    output logic sop1_o,
    output logic sop2_o,
    output logic nreset_o,
    input  logic host_irq_i,
    input  logic nerror_out_i
);

  logic [AXIS_DATA_W-1:0]   rd_axis_tdata_unused;
  logic [AXIS_DATA_W/8-1:0] rd_axis_tkeep_unused;
  logic                     rd_axis_tvalid_unused;
  logic                     rd_axis_tlast_unused;
  logic [AXIS_USER_W-1:0]   rd_axis_tuser_unused;

  awr2243_capture_top_exec #(
      .AXIS_DATA_W(AXIS_DATA_W),
      .AXIS_USER_W(AXIS_USER_W),
      .AXIL_ADDR_W(AXIL_ADDR_W),
      .AXIL_DATA_W(AXIL_DATA_W),
      .AXI_ADDR_W (AXI_ADDR_W),
      .AXI_DATA_W (AXI_DATA_W)
  ) u_exec (
      .sys_clk              (axi_clk),
      .sys_rst_n            (axi_rst_n),
      .axi_clk              (axi_clk),
      .axi_rst_n            (axi_rst_n),

      .s_axis_csi_tdata     (s_axis_csi_tdata),
      .s_axis_csi_tkeep     (s_axis_csi_tkeep),
      .s_axis_csi_tvalid    (s_axis_csi_tvalid),
      .s_axis_csi_tready    (s_axis_csi_tready),
      .s_axis_csi_tlast     (s_axis_csi_tlast),
      .s_axis_csi_tuser     (s_axis_csi_tuser),

      .s_axil_bar0_awaddr   (s_axil_bar0_awaddr),
      .s_axil_bar0_awprot   (s_axil_bar0_awprot),
      .s_axil_bar0_awvalid  (s_axil_bar0_awvalid),
      .s_axil_bar0_awready  (s_axil_bar0_awready),
      .s_axil_bar0_wdata    (s_axil_bar0_wdata),
      .s_axil_bar0_wstrb    (s_axil_bar0_wstrb),
      .s_axil_bar0_wvalid   (s_axil_bar0_wvalid),
      .s_axil_bar0_wready   (s_axil_bar0_wready),
      .s_axil_bar0_bresp    (s_axil_bar0_bresp),
      .s_axil_bar0_bvalid   (s_axil_bar0_bvalid),
      .s_axil_bar0_bready   (s_axil_bar0_bready),
      .s_axil_bar0_araddr   (s_axil_bar0_araddr),
      .s_axil_bar0_arprot   (s_axil_bar0_arprot),
      .s_axil_bar0_arvalid  (s_axil_bar0_arvalid),
      .s_axil_bar0_arready  (s_axil_bar0_arready),
      .s_axil_bar0_rdata    (s_axil_bar0_rdata),
      .s_axil_bar0_rresp    (s_axil_bar0_rresp),
      .s_axil_bar0_rvalid   (s_axil_bar0_rvalid),
      .s_axil_bar0_rready   (s_axil_bar0_rready),

      .m_axi_awaddr         (m_axi_awaddr),
      .m_axi_awlen          (m_axi_awlen),
      .m_axi_awsize         (m_axi_awsize),
      .m_axi_awburst        (m_axi_awburst),
      .m_axi_awvalid        (m_axi_awvalid),
      .m_axi_awready        (m_axi_awready),
      .m_axi_wdata          (m_axi_wdata),
      .m_axi_wstrb          (m_axi_wstrb),
      .m_axi_wlast          (m_axi_wlast),
      .m_axi_wvalid         (m_axi_wvalid),
      .m_axi_wready         (m_axi_wready),
      .m_axi_bresp          (m_axi_bresp),
      .m_axi_bvalid         (m_axi_bvalid),
      .m_axi_bready         (m_axi_bready),
      .m_axi_araddr         (m_axi_araddr),
      .m_axi_arlen          (m_axi_arlen),
      .m_axi_arsize         (m_axi_arsize),
      .m_axi_arburst        (m_axi_arburst),
      .m_axi_arvalid        (m_axi_arvalid),
      .m_axi_arready        (m_axi_arready),
      .m_axi_rdata          (m_axi_rdata),
      .m_axi_rresp          (m_axi_rresp),
      .m_axi_rlast          (m_axi_rlast),
      .m_axi_rvalid         (m_axi_rvalid),
      .m_axi_rready         (m_axi_rready),

      .m_axis_rd_tdata      (rd_axis_tdata_unused),
      .m_axis_rd_tkeep      (rd_axis_tkeep_unused),
      .m_axis_rd_tvalid     (rd_axis_tvalid_unused),
      .m_axis_rd_tready     (1'b1),
      .m_axis_rd_tlast      (rd_axis_tlast_unused),
      .m_axis_rd_tuser      (rd_axis_tuser_unused),

      .spi_sclk_o           (spi_sclk_o),
      .spi_cs_n_o           (spi_cs_n_o),
      .spi_mosi_o           (spi_mosi_o),
      .spi_miso_i           (spi_miso_i),
      .sop0_o               (sop0_o),
      .sop1_o               (sop1_o),
      .sop2_o               (sop2_o),
      .nreset_o             (nreset_o),
      .host_irq_i           (host_irq_i),
      .nerror_out_i         (nerror_out_i),

      .pkt_start_o          (),
      .pkt_done_o           (),
      .pkt_valid_good_o     (),
      .pkt_seq_o            (),
      .pkt_bytes_o          (),
      .pkt_crc_err_o        (),
      .pkt_ecc_err_o        (),
      .pkt_trunc_err_o      (),
      .slot_start_o         (),
      .slot_done_o          (),
      .slot_bytes_o         (),
      .slot_seq_o           (),
      .slot_valid_good_o    (),
      .slot_overflow_err_o  (),
      .wr_slot_commit_o     (),
      .wr_slot_addr_o       (),
      .wr_slot_seq_o        (),
      .wr_slot_bytes_o      (),
      .wr_slot_valid_good_o (),
      .wr_slot_overflow_err_o(),
      .rd_slot_valid_o      (),
      .rd_slot_addr_o       (),
      .rd_slot_bytes_o      (),
      .rd_slot_seq_o        (),
      .rd_slot_valid_good_o (),
      .rd_slot_overflow_err_o(),
      .rd_busy_o            (),
      .rd_done_o            (),
      .rd_error_o           (),
      .wr_ptr_o             (),
      .rd_ptr_o             (),
      .commit_ptr_o         (),
      .used_bytes_o         (),
      .free_bytes_o         (),
      .committed_bytes_o    (),
      .full_o               (),
      .almost_full_o        (),
      .empty_o              (),
      .wrap_count_o         (),
      .overflow_count_o     (),
      .drop_count_o         (),
      .err_cfg_align_o      (),
      .err_no_space_o       (),
      .err_slot_proto_o     (),
      .err_slot_too_large_o (),
      .err_axi_wr_resp_o    (),
      .err_axi_rd_resp_o    (),
      .err_illegal_read_o   (),
      .ctrl_busy_o          (),
      .ctrl_done_o          (),
      .ctrl_err_code_o      (),
      .ctrl_state_o         ()
  );

endmodule
