`timescale 1ns / 1ps

module awr2243_capture_core_ref #(
    parameter integer AXIS_DATA_W = 256,
    parameter integer AXIS_USER_W = 64,
    parameter integer AXIL_ADDR_W = 32,
    parameter integer AXIL_DATA_W = 32,
    parameter integer AXI_ADDR_W  = 34,
    parameter integer AXI_DATA_W  = 256
) (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 axi_clk CLK", X_INTERFACE_PARAMETER = "FREQ_HZ 250000000, ASSOCIATED_BUSIF s_axis_csi:s_axil_bar0:m_axi, ASSOCIATED_RESET axi_rst_n" *)
    input  wire                      axi_clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 axi_rst_n RST", X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire                      axi_rst_n,

    input  wire [AXIS_DATA_W-1:0]    s_axis_csi_tdata,
    input  wire [AXIS_DATA_W/8-1:0]  s_axis_csi_tkeep,
    input  wire                      s_axis_csi_tvalid,
    output wire                      s_axis_csi_tready,
    input  wire                      s_axis_csi_tlast,
    input  wire [AXIS_USER_W-1:0]    s_axis_csi_tuser,

    input  wire [AXIL_ADDR_W-1:0]    s_axil_bar0_awaddr,
    input  wire [2:0]                s_axil_bar0_awprot,
    input  wire                      s_axil_bar0_awvalid,
    output wire                      s_axil_bar0_awready,
    input  wire [AXIL_DATA_W-1:0]    s_axil_bar0_wdata,
    input  wire [AXIL_DATA_W/8-1:0]  s_axil_bar0_wstrb,
    input  wire                      s_axil_bar0_wvalid,
    output wire                      s_axil_bar0_wready,
    output wire [1:0]                s_axil_bar0_bresp,
    output wire                      s_axil_bar0_bvalid,
    input  wire                      s_axil_bar0_bready,
    input  wire [AXIL_ADDR_W-1:0]    s_axil_bar0_araddr,
    input  wire [2:0]                s_axil_bar0_arprot,
    input  wire                      s_axil_bar0_arvalid,
    output wire                      s_axil_bar0_arready,
    output wire [AXIL_DATA_W-1:0]    s_axil_bar0_rdata,
    output wire [1:0]                s_axil_bar0_rresp,
    output wire                      s_axil_bar0_rvalid,
    input  wire                      s_axil_bar0_rready,

    output wire [AXI_ADDR_W-1:0]     m_axi_awaddr,
    output wire [7:0]                m_axi_awlen,
    output wire [2:0]                m_axi_awsize,
    output wire [1:0]                m_axi_awburst,
    output wire                      m_axi_awvalid,
    input  wire                      m_axi_awready,
    output wire [AXI_DATA_W-1:0]     m_axi_wdata,
    output wire [AXI_DATA_W/8-1:0]   m_axi_wstrb,
    output wire                      m_axi_wlast,
    output wire                      m_axi_wvalid,
    input  wire                      m_axi_wready,
    input  wire [1:0]                m_axi_bresp,
    input  wire                      m_axi_bvalid,
    output wire                      m_axi_bready,
    output wire [AXI_ADDR_W-1:0]     m_axi_araddr,
    output wire [7:0]                m_axi_arlen,
    output wire [2:0]                m_axi_arsize,
    output wire [1:0]                m_axi_arburst,
    output wire                      m_axi_arvalid,
    input  wire                      m_axi_arready,
    input  wire [AXI_DATA_W-1:0]     m_axi_rdata,
    input  wire [1:0]                m_axi_rresp,
    input  wire                      m_axi_rlast,
    input  wire                      m_axi_rvalid,
    output wire                      m_axi_rready,

    output wire                      spi_sclk_o,
    output wire                      spi_cs_n_o,
    output wire                      spi_mosi_o,
    input  wire                      spi_miso_i,
    output wire                      sop0_o,
    output wire                      sop1_o,
    output wire                      sop2_o,
    output wire                      nreset_o,
    input  wire                      host_irq_i,
    input  wire                      nerror_out_i
);

  awr2243_capture_core_impl #(
      .AXIS_DATA_W(AXIS_DATA_W),
      .AXIS_USER_W(AXIS_USER_W),
      .AXIL_ADDR_W(AXIL_ADDR_W),
      .AXIL_DATA_W(AXIL_DATA_W),
      .AXI_ADDR_W (AXI_ADDR_W),
      .AXI_DATA_W (AXI_DATA_W)
  ) impl (
      .axi_clk            (axi_clk),
      .axi_rst_n          (axi_rst_n),
      .s_axis_csi_tdata   (s_axis_csi_tdata),
      .s_axis_csi_tkeep   (s_axis_csi_tkeep),
      .s_axis_csi_tvalid  (s_axis_csi_tvalid),
      .s_axis_csi_tready  (s_axis_csi_tready),
      .s_axis_csi_tlast   (s_axis_csi_tlast),
      .s_axis_csi_tuser   (s_axis_csi_tuser),
      .s_axil_bar0_awaddr (s_axil_bar0_awaddr),
      .s_axil_bar0_awprot (s_axil_bar0_awprot),
      .s_axil_bar0_awvalid(s_axil_bar0_awvalid),
      .s_axil_bar0_awready(s_axil_bar0_awready),
      .s_axil_bar0_wdata  (s_axil_bar0_wdata),
      .s_axil_bar0_wstrb  (s_axil_bar0_wstrb),
      .s_axil_bar0_wvalid (s_axil_bar0_wvalid),
      .s_axil_bar0_wready (s_axil_bar0_wready),
      .s_axil_bar0_bresp  (s_axil_bar0_bresp),
      .s_axil_bar0_bvalid (s_axil_bar0_bvalid),
      .s_axil_bar0_bready (s_axil_bar0_bready),
      .s_axil_bar0_araddr (s_axil_bar0_araddr),
      .s_axil_bar0_arprot (s_axil_bar0_arprot),
      .s_axil_bar0_arvalid(s_axil_bar0_arvalid),
      .s_axil_bar0_arready(s_axil_bar0_arready),
      .s_axil_bar0_rdata  (s_axil_bar0_rdata),
      .s_axil_bar0_rresp  (s_axil_bar0_rresp),
      .s_axil_bar0_rvalid (s_axil_bar0_rvalid),
      .s_axil_bar0_rready (s_axil_bar0_rready),
      .m_axi_awaddr       (m_axi_awaddr),
      .m_axi_awlen        (m_axi_awlen),
      .m_axi_awsize       (m_axi_awsize),
      .m_axi_awburst      (m_axi_awburst),
      .m_axi_awvalid      (m_axi_awvalid),
      .m_axi_awready      (m_axi_awready),
      .m_axi_wdata        (m_axi_wdata),
      .m_axi_wstrb        (m_axi_wstrb),
      .m_axi_wlast        (m_axi_wlast),
      .m_axi_wvalid       (m_axi_wvalid),
      .m_axi_wready       (m_axi_wready),
      .m_axi_bresp        (m_axi_bresp),
      .m_axi_bvalid       (m_axi_bvalid),
      .m_axi_bready       (m_axi_bready),
      .m_axi_araddr       (m_axi_araddr),
      .m_axi_arlen        (m_axi_arlen),
      .m_axi_arsize       (m_axi_arsize),
      .m_axi_arburst      (m_axi_arburst),
      .m_axi_arvalid      (m_axi_arvalid),
      .m_axi_arready      (m_axi_arready),
      .m_axi_rdata        (m_axi_rdata),
      .m_axi_rresp        (m_axi_rresp),
      .m_axi_rlast        (m_axi_rlast),
      .m_axi_rvalid       (m_axi_rvalid),
      .m_axi_rready       (m_axi_rready),
      .spi_sclk_o         (spi_sclk_o),
      .spi_cs_n_o         (spi_cs_n_o),
      .spi_mosi_o         (spi_mosi_o),
      .spi_miso_i         (spi_miso_i),
      .sop0_o             (sop0_o),
      .sop1_o             (sop1_o),
      .sop2_o             (sop2_o),
      .nreset_o           (nreset_o),
      .host_irq_i         (host_irq_i),
      .nerror_out_i       (nerror_out_i)
  );

endmodule
